### ISSUE TITLE
Errors with Dokuwiki 2023-04-04 "Jack Jackrum"  - PHP 8.1

### ISSUE THREAD

**Issue by Miro-Collas** [roquess/dokuwiki-plugin-iframeinterwiki#1]
Right after installing this plugin:

```
TypeError: fgets(): Argument #1 ($stream) must be of type resource, bool given

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the iframeinterwiki plugin.

More info has been written to the DokuWiki error log.
```

Error log:

```
2023-08-13 21:25:07E_WARNING: fopen(/home/fswiki/public_html/conf/interwiki.local.conf): Failed to open stream: No such file or directory/home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php(79)
    #0 [internal function]: dokuwiki\ErrorHandler::errorHandler(2, 'fopen(/home/fsw...', '/home/fswiki/pu...', 79)
    #1 /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php(79): fopen('/home/fswiki/pu...', 'r')
    #2 /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php(106): syntax_plugin_iframeinterwiki->parse_uri_inter('https://teamup....', '/home/fswiki/pu...')
    #3 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_iframeinterwiki->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #4 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('iframeinterwiki', Array, 5, '{{url>https://t...')
    #5 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #6 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'firestorm_class...')
    #7 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('firestorm_class...', 0, true, '')
    #8 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #9 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #10 [internal function]: tpl_content_core('show')
    #11 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #12 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #13 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #14 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #15 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #16 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #17 {main}
2023-08-13 21:25:07TypeError: fgets(): Argument #1 ($stream) must be of type resource, bool given/home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php(80)
    #0 /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php(80): fgets(false)
    #1 /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php(106): syntax_plugin_iframeinterwiki->parse_uri_inter('https://teamup....', '/home/fswiki/pu...')
    #2 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_iframeinterwiki->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #3 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('iframeinterwiki', Array, 5, '{{url>https://t...')
    #4 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #5 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'firestorm_class...')
    #6 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('firestorm_class...', 0, true, '')
    #7 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #8 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #9 [internal function]: tpl_content_core('show')
    #10 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #11 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #12 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #13 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #14 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #15 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #16 {main}
```

Deprecated log:

```
2023-08-13 21:21:26require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php:14 Autoloading should be used instead!
2023-08-13 21:21:31require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php:14 Autoloading should be used instead!
2023-08-13 21:21:54require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php:14 Autoloading should be used instead!
2023-08-13 21:22:26require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php:14 Autoloading should be used instead!
2023-08-13 21:22:30require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php:14 Autoloading should be used instead!
2023-08-13 21:22:30resolve_pageid() is deprecated. It was called from syntax_plugin_pageredirect::handle() in /home/fswiki/public_html/lib/plugins/pageredirect/syntax.php:81 dokuwiki\File\PageResolver should be used instead!
2023-08-13 21:22:31require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php:14 Autoloading should be used instead!
2023-08-13 21:22:31resolve_pageid() is deprecated. It was called from syntax_plugin_pageredirect::handle() in /home/fswiki/public_html/lib/plugins/pageredirect/syntax.php:81 dokuwiki\File\PageResolver should be used instead!
2023-08-13 21:22:31require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/iframeinterwiki/syntax.php:14 Autoloading should be used instead!
```

**Comment by roquess** [comment]
Hello, removing some warning. Fix opening conf file error by check exists.
